apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      run: app
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: $IMAGE
      - ports:
        containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    run: app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
